// Erkaklar kiyimlari katalogi
// Toifalar: futbolkalar, shimlar, kurtkalar, oyoq-kiyimlar
// Ichki kiyimlar kiritilmagan.

const PRODUCTS = [
  // ==================== FUTBOLKALAR ====================
  {
    id: 1,
    category: "futbolkalar",
    categoryName: "Futbolka",
    name: "Premium Oversize Qora Futbolka",
    price: 165000,
    oldPrice: 210000,
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["Qora", "To'q kulrang"],
    badge: "Hit Mahsulot",
    rating: 4.9,
    reviewsCount: 38,
    image: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=80",
    description: "100% paxta, premium matodan tayyorlangan qulay oversize erkaklar futbolkasi. Kundalik va ko'cha uslubi uchun a'lo tanlov."
  },
  {
    id: 2,
    category: "futbolkalar",
    categoryName: "Futbolka",
    name: "Klassik Oq Polo Futbolka",
    price: 195000,
    oldPrice: 250000,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Oq", "To'q ko'k"],
    badge: "Yangi",
    rating: 4.8,
    reviewsCount: 24,
    image: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800&auto=format&fit=crop&q=80",
    description: "Yoqali klassik polo futbolka. Nafas oluvchi zich paxta matosi, ishxona va do'stlar davrasi uchun ajoyib qiyofa yaratadi."
  },
  {
    id: 3,
    category: "futbolkalar",
    categoryName: "Futbolka",
    name: "Zaytun Rangi Sport Futbolka",
    price: 145000,
    oldPrice: 180000,
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["Zaytun yashil", "Qora"],
    badge: null,
    rating: 4.7,
    reviewsCount: 19,
    image: "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800&auto=format&fit=crop&q=80",
    description: "Yengil va elastik sport uslubidagi erkaklar futbolkasi. Faol mashg'ulotlar va issiq kunlar uchun juda qulay."
  },
  {
    id: 4,
    category: "futbolkalar",
    categoryName: "Futbolka",
    name: "Bej Oversize Minimalist Futbolka",
    price: 175000,
    oldPrice: 220000,
    sizes: ["S", "M", "L", "XL"],
    colors: ["Bej", "Oq"],
    badge: "Trend",
    rating: 5.0,
    reviewsCount: 45,
    image: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800&auto=format&fit=crop&q=80",
    description: "Zamonaviy bej rangdagi qalin paxtali futbolka. Shaklini yo'qotmaydi, yuvganda rangi o'chmaydi."
  },
  {
    id: 5,
    category: "futbolkalar",
    categoryName: "Futbolka",
    name: "To'q Moviy Striped Polo Futbolka",
    price: 210000,
    oldPrice: 260000,
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["To'q moviy", "Kulrang"],
    badge: null,
    rating: 4.8,
    reviewsCount: 15,
    image: "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&auto=format&fit=crop&q=80",
    description: "Chiziqli yoqali erkaklar polosi. Rasmiy va erkin uslub uyg'unligi, sifatli furnitura."
  },
  {
    id: 6,
    category: "futbolkalar",
    categoryName: "Futbolka",
    name: "Urban Grafika Print Futbolka",
    price: 155000,
    oldPrice: 195000,
    sizes: ["M", "L", "XL"],
    colors: ["Qora", "Oq"],
    badge: "Chegirma",
    rating: 4.6,
    reviewsCount: 31,
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&auto=format&fit=crop&q=80",
    description: "Orqa tomonida sifatli chidamli bosma printga ega yoshlarbop zamonaviy futbolka."
  },

  // ==================== TRIKO VA SHIMLAR ====================
  {
    id: 7,
    category: "shimlar",
    categoryName: "Shim va Triko",
    name: "Qora Kargo Cho'ntakli Shim",
    price: 285000,
    oldPrice: 350000,
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Qora", "Xaki"],
    badge: "Hit Mahsulot",
    rating: 4.9,
    reviewsCount: 52,
    image: "https://images.unsplash.com/photo-1517445312882-bc9910d016b7?w=800&auto=format&fit=crop&q=80",
    description: "Ko'p cho'ntakli kargo shim. Zich va mustahkam mato, zamonaviy erkin bichim, bel qismi qulay rezinada."
  },
  {
    id: 8,
    category: "shimlar",
    categoryName: "Shim va Triko",
    name: "Qulay Paxtali Sport Triko (Jogger)",
    price: 220000,
    oldPrice: 280000,
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["Kulrang", "Qora"],
    badge: "Yangi",
    rating: 4.8,
    reviewsCount: 41,
    image: "https://images.unsplash.com/photo-1552902865-b72c031ac5ea?w=800&auto=format&fit=crop&q=80",
    description: "Yumshoq 3 ipli paxta triko matosidan tayyorlangan jogger. Sport va uy, ko'cha sayrlari uchun ideal qulaylik."
  },
  {
    id: 9,
    category: "shimlar",
    categoryName: "Shim va Triko",
    name: "Klassik Chinos Shimi (Bej)",
    price: 295000,
    oldPrice: 360000,
    sizes: ["30", "31", "32", "33", "34", "36"],
    colors: ["Bej", "To'q ko'k"],
    badge: "Klassika",
    rating: 4.9,
    reviewsCount: 33,
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800&auto=format&fit=crop&q=80",
    description: "Sifatli paxtali Chinos shimi. Ko'ylak, polo yoki futbolkalar bilan juda kelishgan obraz hosil qiladi."
  },
  {
    id: 10,
    category: "shimlar",
    categoryName: "Shim va Triko",
    name: "Klassik Slim-Fit Moviy Jinsi",
    price: 310000,
    oldPrice: 390000,
    sizes: ["30", "32", "34", "36"],
    colors: ["Moviy", "Qora-kulrang"],
    badge: null,
    rating: 4.7,
    reviewsCount: 29,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=80",
    description: "Sifatli denim matosidan tayyorlangan zamonaviy jinsi shim. Elastik qo'shimchasi tufayli harakatni cheklamaydi."
  },
  {
    id: 11,
    category: "shimlar",
    categoryName: "Shim va Triko",
    name: "To'q Ko'k Ofis Shimi",
    price: 330000,
    oldPrice: 400000,
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["To'q ko'k", "Qora"],
    badge: null,
    rating: 4.8,
    reviewsCount: 22,
    image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&auto=format&fit=crop&q=80",
    description: "G'ijimlanmaydigan sifatli matodan tikilgan to'g'ri bichimli rasmiy erkaklar shimi."
  },
  {
    id: 12,
    category: "shimlar",
    categoryName: "Shim va Triko",
    name: "Qora Streetwear Keng Triko",
    price: 240000,
    oldPrice: 295000,
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["Qora", "Antratsit"],
    badge: "Trend",
    rating: 4.9,
    reviewsCount: 36,
    image: "https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=800&auto=format&fit=crop&q=80",
    description: "Erkin uslubdagi qulay keng triko. Oyoq pastki qismi to'g'ri tushuvchi erkin bichim."
  },

  // ==================== KURTKALAR ====================
  {
    id: 13,
    category: "kurtkalar",
    categoryName: "Kurtka",
    name: "Qora Bayker Charm Kurtka",
    price: 680000,
    oldPrice: 850000,
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["Qora"],
    badge: "Premial",
    rating: 5.0,
    reviewsCount: 64,
    image: "https://images.unsplash.com/photo-1520975954732-35dd22299614?w=800&auto=format&fit=crop&q=80",
    description: "Haqiqiy erkaklar uchun mo'ljallangan mustahkam charm kurtka. Shamol o'tkazmaydi, metall zamokli va qulay cho'ntaklar."
  },
  {
    id: 14,
    category: "kurtkalar",
    categoryName: "Kurtka",
    name: "Mavsumiy Bomba Kurtka (Bomber)",
    price: 430000,
    oldPrice: 520000,
    sizes: ["S", "M", "L", "XL", "2XL"],
    colors: ["Zaytun", "Qora"],
    badge: "Hit",
    rating: 4.8,
    reviewsCount: 47,
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&auto=format&fit=crop&q=80",
    description: "Bahor va kuz oylari uchun yengil va issiq bombardimonchi kurtka. Qulay yoqa va yenglari rezinada."
  },
  {
    id: 15,
    category: "kurtkalar",
    categoryName: "Kurtka",
    name: "Klassik Issiq Denim Jinsi Kurtka",
    price: 460000,
    oldPrice: 560000,
    sizes: ["M", "L", "XL"],
    colors: ["Moviy denim", "Qora denim"],
    badge: null,
    rating: 4.7,
    reviewsCount: 30,
    image: "https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800&auto=format&fit=crop&q=80",
    description: "Zich denim matosi, ichki qismi qulay paxta astarli. Doim urfda bo'ladigan klassik erkaklar jinsi kurtkasi."
  },
  {
    id: 16,
    category: "kurtkalar",
    categoryName: "Kurtka",
    name: "Shamol va Yomg'irdan Himoyali Vetrovka",
    price: 360000,
    oldPrice: 440000,
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["Qora/Kulrang", "To'q ko'k"],
    badge: "Yangi",
    rating: 4.8,
    reviewsCount: 26,
    image: "https://images.unsplash.com/photo-1544441893-675973e31985?w=800&auto=format&fit=crop&q=80",
    description: "Suv yuqmaydigan membranali engil vetrovka. Kapushoni sozlanuvchi, sport va tog' sayrlari uchun mo'ljallangan."
  },
  {
    id: 17,
    category: "kurtkalar",
    categoryName: "Kurtka",
    name: "Qalin Qishki Puchovik Parka",
    price: 790000,
    oldPrice: 990000,
    sizes: ["L", "XL", "2XL", "3XL"],
    colors: ["Qora", "Xaki"],
    badge: "Maksimal Issiq",
    rating: 4.9,
    reviewsCount: 58,
    image: "https://images.unsplash.com/photo-1548883354-7622d03aca27?w=800&auto=format&fit=crop&q=80",
    description: "Eng sovuq ob-havoga ham bardosh beruvchi qalin xolfayberli qishki parka kurtka. Mo'ynali kapushon va ko'p cho'ntakli."
  },
  {
    id: 18,
    category: "kurtkalar",
    categoryName: "Kurtka",
    name: "Yengil Issiq Erkaklar Jiletkasi",
    price: 320000,
    oldPrice: 410000,
    sizes: ["M", "L", "XL", "2XL"],
    colors: ["Qora", "To'q ko'k"],
    badge: null,
    rating: 4.7,
    reviewsCount: 35,
    image: "https://images.unsplash.com/photo-1516826957135-700dedea698c?w=800&auto=format&fit=crop&q=80",
    description: "Mashinada yurish va erkin harakatlanish uchun engil, qulay va issiq yengsiz kurtka (jiletka)."
  },

  // ==================== OYOQ KIYIMLAR ====================
  {
    id: 19,
    category: "oyoq-kiyimlar",
    categoryName: "Oyoq Kiyim",
    name: "Oq Kundalik Street Krossovka",
    price: 390000,
    oldPrice: 490000,
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["Oq"],
    badge: "Hit Mahsulot",
    rating: 4.9,
    reviewsCount: 73,
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&auto=format&fit=crop&q=80",
    description: "Har qanday kiyimga yarashuvchi toza oq rangli charm krossovka. Yumshoq taglik va maksimal qulaylik."
  },
  {
    id: 20,
    category: "oyoq-kiyimlar",
    categoryName: "Oyoq Kiyim",
    name: "Sport Air Yugurish Krossovkasi",
    price: 420000,
    oldPrice: 530000,
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: ["Qora/Qizil", "Kulrang"],
    badge: "Yangi",
    rating: 4.8,
    reviewsCount: 39,
    image: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&auto=format&fit=crop&q=80",
    description: "Amortizatsiyali engil taglik. Yugurish, trenirovka va uzoq piyoda yurish uchun oyoqni charchatmaydi."
  },
  {
    id: 21,
    category: "oyoq-kiyimlar",
    categoryName: "Oyoq Kiyim",
    name: "Klassik Charm Oksford Tufli",
    price: 490000,
    oldPrice: 620000,
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: ["Qora", "Jigarrang"],
    badge: "Klassika",
    rating: 4.9,
    reviewsCount: 42,
    image: "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?w=800&auto=format&fit=crop&q=80",
    description: "100% tabiiy charmdan tikilgan rasmiy tadbirlar, to'ylar va ish uchun benuqson klassik tufli."
  },
  {
    id: 22,
    category: "oyoq-kiyimlar",
    categoryName: "Oyoq Kiyim",
    name: "Zamonaviy Qulay Loferlar (Suede)",
    price: 440000,
    oldPrice: 550000,
    sizes: ["40", "41", "42", "43", "44"],
    colors: ["To'q jigarrang", "Bej"],
    badge: "Premial",
    rating: 4.8,
    reviewsCount: 28,
    image: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800&auto=format&fit=crop&q=80",
    description: "Zamsh materialidan qilingan yumshoq lofer. Bog'ichsiz, oson kiyiluvchi va juda xushbichim."
  },
  {
    id: 23,
    category: "oyoq-kiyimlar",
    categoryName: "Oyoq Kiyim",
    name: "Harbiy Uslubdagi Qalin Etik (Boots)",
    price: 580000,
    oldPrice: 720000,
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: ["Qora", "Jigarrang"],
    badge: "Mavsumiy",
    rating: 4.9,
    reviewsCount: 31,
    image: "https://images.unsplash.com/photo-1542280756-74b2f55e73ab?w=800&auto=format&fit=crop&q=80",
    description: "Mustahkam traktor taglikli qalin charm etik. Qishki va sovuq kunlar uchun mukammal himoya va joziba."
  },
  {
    id: 24,
    category: "oyoq-kiyimlar",
    categoryName: "Oyoq Kiyim",
    name: "Qora Minimalist Skate Keda",
    price: 310000,
    oldPrice: 380000,
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: ["Qora", "To'q kulrang"],
    badge: null,
    rating: 4.7,
    reviewsCount: 44,
    image: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&auto=format&fit=crop&q=80",
    description: "Yengil tekis taglikli mustahkam keda. Jinsi va trikolar bilan ajoyib mos tushadi."
  }
];

// O'zbek so'mida formatlash yordamchisi
function formatPrice(price) {
  return price.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ") + " so'm";
}
